esphome:
  name: standing-desk
  friendly_name: Standing Desk

esp8266:
  board: nodemcuv2
  framework:
    version: recommended

logger:

api:
  encryption:
    key: !secret api_password 

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Standing-Desk Fallback Hotspot"
    password: !secret fallback_password

  manual_ip:
    static_ip: 192.168.178.53
    gateway: 192.168.178.1
    subnet: 255.255.255.0

external_components: 
  - source: ./custom_components
    components: [ standing_desk_sensor ]

switch:
  - platform: gpio 
    name: Up
    id: up_btn
    icon: "mdi:arrow-up-bold"
    pin: 
      number: GPIO12
      inverted: true

  - platform: gpio 
    name: Down 
    id: down_btn
    icon: "mdi:arrow-down-bold"
    pin: 
      number: GPIO13
      inverted: true

  - platform: template 
    name: Mem1 
    id: mem1_btn
    icon: "mdi:numeric-1-box-outline"
    turn_on_action: 
      - switch.turn_on: up_btn
      - switch.turn_on: down_btn
    turn_off_action: 
      - switch.turn_off: up_btn
      - switch.turn_off: down_btn

  - platform: gpio 
    name: Mem2 
    id: mem2_btn
    icon: "mdi:numeric-2-box-outline"
    pin: 
      number: GPIO14
      inverted: true

  - platform: template 
    name: Mem3 
    id: mem3_btn
    icon: "mdi:numeric-3-box-outline"
    turn_on_action: 
      - switch.turn_on: mem2_btn
      - switch.turn_on: down_btn
    turn_off_action: 
      - switch.turn_off: mem2_btn
      - switch.turn_off: down_btn

sensor:
  - platform: standing_desk_sensor
    name: "Height"
    id: "height"
    unit_of_measurement: "cm"

uart: 
  rx_pin: D9 
  tx_pin: D10 
  baud_rate: 9600
