esphome:
  name: standing-desk
  friendly_name: Standing Desk

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: !secret api_password 

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Standing-Desk Fallback Hotspot"
    password: !secret fallback_password

  manual_ip:
    static_ip: 192.168.178.53
    gateway: 192.168.178.1
    subnet: 255.255.255.0

external_components: 
  - source: ./custom_components
    components: [ standing_desk_sensor ]

button:
  - platform: template 
    name: Up 
    id: up_btn
    icon: "mdi:arrow-up-bold"

  - platform: template 
    name: Down 
    id: down_btn
    icon: "mdi:arrow-down-bold"

  - platform: template 
    name: Mem1 
    id: mem1_btn
    icon: "mdi:numeric-1-box-outline"

  - platform: template 
    name: Mem2 
    id: mem2_btn
    icon: "mdi:numeric-2-box-outline"

  - platform: template 
    name: Mem3 
    id: mem3_btn
    icon: "mdi:numeric-3-box-outline"

sensor:
  - platform: standing_desk_sensor
    name: "Height"
    id: "height"
    unit_of_measurement: "cm"

uart: 
  rx_pin: 16 
  tx_pin: 17
  baud_rate: 9600
